# Generated by Django 6.1 on 2026-08-18 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "theme_color",
                    models.CharField(
                        default="#2c3e50",
                        help_text="Hex color code for theme",
                        max_length=7,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("ISSUE", "Issue Certificate"),
                            ("REVOKE", "Revoke Certificate"),
                            ("VERIFY", "Verify Certificate"),
                            ("EXPORT", "Export"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_type", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.CharField(max_length=255)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("changes", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="users_audit_action_e79129_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="users_audit_object__f792c7_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="users_audit_timesta_f4ba63_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuthorizedSignatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "title",
                    models.CharField(help_text="Designation/Title", max_length=255),
                ),
                ("organization", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "signature_image",
                    models.ImageField(
                        upload_to="signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="users_autho_is_acti_6d79b7_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="users_autho_organiz_ac273f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique student identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=255)),
                ("university", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=100)),
                ("graduation_year", models.IntegerField()),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/profiles/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Students",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student_id"], name="users_stude_student_908f14_idx"
                    ),
                    models.Index(fields=["email"], name="users_stude_email_9a6210_idx"),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="users_stude_is_acti_332252_idx",
                    ),
                ],
            },
        ),
    ]
