# Generated by Django 6.1 on 2026-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique student identifier",
                max_length=50,
                unique=True,
            ),
        ),
    ]
