# Generated by Django 6.1 on 2026-08-26 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="certificate_footer",
            field=models.TextField(
                blank=True,
                help_text="Custom footer notice or legal text displayed at the bottom of certificates",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Official name of the issuing company or organization",
                max_length=255,
                verbose_name="Company Name",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="description",
            field=models.TextField(
                blank=True, help_text="Company description or mission statement"
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="address",
            field=models.TextField(
                blank=True, help_text="Company physical or registered address"
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Official contact email", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo displayed on certificates and public portal",
                null=True,
                upload_to="company/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="Organization name (legacy/alias)",
                max_length=255,
                verbose_name="Organization Name",
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Official contact phone number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="companysettings",
            name="website",
            field=models.URLField(
                blank=True, help_text="Official website URL", null=True
            ),
        ),
    ]
