# Generated by Django 6.1 on 2026-08-26 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_companysettings_certificate_footer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorizedsignatory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Authorized Signatory",
                "verbose_name_plural": "Authorized Signatories",
            },
        ),
        migrations.AlterField(
            model_name="authorizedsignatory",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="authorizedsignatory",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Signatory Name"),
        ),
        migrations.AlterField(
            model_name="authorizedsignatory",
            name="organization",
            field=models.CharField(
                blank=True, help_text="Organization name (optional)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="authorizedsignatory",
            name="signature_image",
            field=models.ImageField(
                help_text="Official signature image",
                upload_to="signatures/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="authorizedsignatory",
            name="title",
            field=models.CharField(
                help_text="Official designation/title (e.g. Director, Dean)",
                max_length=255,
                verbose_name="Designation",
            ),
        ),
    ]
