# Generated by Django 6.1 on 2026-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_authorizedsignatory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("ISSUE", "Issue Certificate"),
                    ("REVOKE", "Revoke Certificate"),
                    ("VERIFY", "Verify Certificate"),
                    ("EMAIL", "Send Email"),
                    ("EXPORT", "Export"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
