# Generated by Django 6.1 on 2026-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("ISSUE", "Issue Certificate"),
                    ("DOWNLOAD", "Download Certificate"),
                    ("VERIFY", "Verify Certificate"),
                    ("REVOKE", "Revoke Certificate"),
                    ("REGENERATE", "Regenerate Certificate"),
                    ("EMAIL", "Send Email"),
                    ("EXPORT", "Export"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user_email", "-timestamp"],
                name="users_audit_user_em_342122_idx",
            ),
        ),
    ]
