# Generated by Django 6.1 on 2026-08-18 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("organization", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "html_template",
                    models.TextField(help_text="HTML template for certificate"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="templates/logos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="templates/signatures/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        default=dict, help_text="Color configuration as JSON"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="certificate_is_acti_4f5823_idx"
                    ),
                    models.Index(
                        fields=["organization"], name="certificate_organiz_2a98ca_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique program identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("INTERNSHIP", "Internship"),
                            ("COURSE", "Course"),
                            ("WORKSHOP", "Workshop"),
                            ("CERTIFICATION", "Certification"),
                            ("TRAINING", "Training"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("duration", models.IntegerField(help_text="Duration in days")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(max_length=255)),
                (
                    "skills",
                    models.JSONField(default=list, help_text="List of skills covered"),
                ),
                (
                    "learning_outcomes",
                    models.JSONField(
                        default=list, help_text="List of learning outcomes"
                    ),
                ),
                ("mentor", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program_id"], name="certificate_program_f00d9c_idx"
                    ),
                    models.Index(
                        fields=["program_type", "is_active"],
                        name="certificate_program_9bfbd3_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="certificate_is_acti_56a6b3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique enrollment identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField()),
                ("duration", models.IntegerField(help_text="Duration in days")),
                ("mentor", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
                ("project_title", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                ("skills", models.JSONField(default=list, help_text="Skills acquired")),
                (
                    "learning_outcomes",
                    models.JSONField(default=list, help_text="Outcomes achieved"),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "performance_rating",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Rating from 1-5",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("DROPPED", "Dropped"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="ONGOING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="users.student",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="certificates.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique certificate identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Cryptographic token for verification",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("INTERNSHIP", "Internship Certificate"),
                            ("COURSE", "Course Certificate"),
                            ("WORKSHOP", "Workshop Certificate"),
                            ("ACHIEVEMENT", "Achievement Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(db_index=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("duration", models.IntegerField(help_text="Duration in days")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "certificate_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        help_text="QR code value or URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
                (
                    "authorized_signatory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_certificates",
                        to="users.authorizedsignatory",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="users.student",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to="certificates.certificatetemplate",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="certificates.enrollment",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="certificates.program",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Certificates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["enrollment_id"], name="certificate_enrollm_85723f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="certificate_student_9233a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["program", "status"], name="certificate_program_df92bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["status", "-created_at"], name="certificate_status_f27842_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "program", "start_date")},
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["certificate_id"], name="certificate_certifi_5672de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["verification_token"], name="certificate_verific_369807_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["student", "status"], name="certificate_student_16729a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["program", "status"], name="certificate_program_a85e87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["status", "-created_at"], name="certificate_status_c14213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["issue_date", "status"], name="certificate_issue_d_f84255_idx"
            ),
        ),
    ]
