# Generated by Django 6.1 on 2026-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique program identifier",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("INTERNSHIP", "Internship"),
                    ("TRAINING", "Training"),
                    ("WORKSHOP", "Workshop"),
                    ("INDUSTRIAL_TRAINING", "Industrial Training"),
                    ("CERTIFICATION_PROGRAM", "Certification Program"),
                ],
                max_length=50,
            ),
        ),
    ]
