# Generated by Django 6.1 on 2026-08-25 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_alter_program_program_id_alter_program_program_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="QR code image for certificate verification",
                null=True,
                upload_to="certificates/qr_codes/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique enrollment identifier",
                max_length=50,
                unique=True,
            ),
        ),
    ]
