# Generated by Django 6.1 on 2026-08-26 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0003_alter_certificate_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetemplate",
            name="design_style",
            field=models.CharField(
                choices=[
                    ("CLASSIC", "Classic Design (Traditional Ornate)"),
                    ("MODERN", "Modern Design (Minimalist Gradient)"),
                    ("PROFESSIONAL", "Professional Design (Corporate Executive)"),
                ],
                db_index=True,
                default="CLASSIC",
                help_text="Design style layout for certificate rendering",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="colors",
            field=models.JSONField(
                blank=True, default=dict, help_text="Color configuration as JSON"
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="html_template",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Custom template path or override (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="templates/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="organization",
            field=models.CharField(
                blank=True, help_text="Organization name (optional)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="certificatetemplate",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="templates/signatures/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="certificatetemplate",
            index=models.Index(
                fields=["design_style"], name="certificate_design__c52bc9_idx"
            ),
        ),
    ]
