# Generated by Django 6.1 on 2026-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0005_seed_default_certificate_templates"),
        ("users", "0005_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="email_sent",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether delivery email has been sent to recipient",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when delivery email was successfully sent",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["email_sent"], name="certificate_email_s_22c75d_idx"
            ),
        ),
    ]
