# Generated by Django 6.1 on 2026-08-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("QR_SCAN", "QR Code Scan"),
                            ("SEARCH", "Database Search"),
                            ("API", "API Call"),
                            ("MANUAL", "Manual Verification"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to="certificates.certificate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Verification Events",
                "ordering": ["-verified_at"],
                "indexes": [
                    models.Index(
                        fields=["certificate", "-verified_at"],
                        name="qrcode_veri_certifi_11f522_idx",
                    ),
                    models.Index(
                        fields=["verification_method", "-verified_at"],
                        name="qrcode_veri_verific_3be5a3_idx",
                    ),
                    models.Index(
                        fields=["-verified_at"], name="qrcode_veri_verifie_3a415e_idx"
                    ),
                ],
            },
        ),
    ]
